api: NA
name: deadByGayfight
main: racer.fund.Main
version: "1.0"
api-version: 1.8

commands:
   gfregister:
      description: register player to deadbyGayfight
      usage: /gfregister [Player Name]
   gfstart:
      description: start the deadbyGayfight
      usage: /gfstart
   gfsetlobby:
      description: set the lobby position
      usage: /gfsetlobby [x, y, z]